package com.demo.mysql.consts;

import java.util.HashSet;
import java.util.Set;

public class Const {
    public static final String FAMILY_NAMES = "赵  钱  孙  李  周  吴  郑  王  冯  陈  褚  卫  蒋  沈  韩  杨  朱  秦  尤  许  何  吕  施  张  孔  曹  严  华  金  魏  陶  姜  戚  谢  邹  喻  柏  水  窦  章  云  苏  潘  葛  奚  范  彭  郎  鲁  韦  昌  马  苗  凤  花  方  俞  任  袁  柳  酆  鲍  史  唐  费  廉  岑  薛  雷  贺  倪  汤  滕  殷  罗  毕  郝  邬  安  常  乐  于  时  傅  皮  卞  齐  康  伍  余  元  卜  顾  孟  平  黄  和  穆  萧  尹  姚  邵  湛  汪  祁  毛  禹  狄  米  贝  明  臧  计  伏  成  戴  谈  宋  茅  庞  熊  纪  舒  屈  项  祝  董  粱  杜  阮  蓝  闵  席  季  麻  强  贾  路  娄  危  江  童  颜  郭  梅  盛  林  刁  钟  徐  邱  骆  高  夏  蔡  田  樊  胡  凌  霍  虞  万  支  柯  昝  管  卢  莫  经  房  裘  缪  干  解  应  宗  丁  宣  贲  邓  郁  单  杭  洪  包  诸  左  石  崔  吉  钮  龚  程  嵇  邢  滑  裴  陆  荣  翁  荀  羊  於  惠  甄  麴  家  封  芮  羿  储  靳  汲  邴  糜  松  井  段  富  巫  乌  焦  巴  弓  牧  隗  山  谷  车  侯  宓  蓬  全  郗  班  仰  秋  仲  伊  宫  宁  仇  栾  暴  甘  钭  厉  戎  祖  武  符  刘  景  詹  束  龙  叶  幸  司  韶  郜  黎  蓟  薄  印  宿  白  怀  蒲  邰  从  鄂  索  咸  籍  赖  卓  蔺  屠  蒙  池  乔  阴  欎  胥  能  苍  双  闻  莘  党  翟  谭  贡  劳  逄  姬  申  扶  堵  冉  宰  郦  雍  舄  璩  桑  桂  濮  牛  寿  通  边  扈  燕  冀  郏  浦  尚  农  温  别  庄  晏  柴  瞿  阎  充  慕  连  茹  习  宦  艾  鱼  容  向  古  易  慎  戈  廖  庾  终  暨  居  衡  步  都  耿  满  弘  匡  国  文  寇  广  禄  阙  东  殴  殳  沃  利  蔚  越  夔  隆  师  巩  厍  聂  晁  勾  敖  融  冷  訾  辛  阚  那  简  饶  空  曾  毋  沙  乜  养  鞠  须  丰  巢  关  蒯  相  查  後  荆  红  游  竺  权  逯  盖  益  桓  公  万俟  司马  上官  欧阳  夏侯  诸葛  闻人  东方  赫连  皇甫  尉迟  公羊  澹台  公冶  宗政  濮阳  淳于  单于  太叔  申屠  公孙  仲孙  轩辕  令狐  钟离  宇文  长孙  慕容  鲜于  闾丘  司徒  司空  亓官  司寇  仉  督  子车  颛孙  端木  巫马  公西  漆雕  乐正  壤驷  公良  拓跋  夹谷  宰父  谷梁  晋  楚  闫  法  汝  鄢  涂  钦  段干  百里  东郭  南门  呼延  归  海  羊舌  微生  岳  帅  缑  亢  况  后  有  琴  梁丘  左丘  东门  西门  商  牟  佘  佴  伯  赏  南宫  墨  哈  谯  笪  年  爱  阳  佟  第五  言  福  百  家  姓  终"
            + " 卓 蔺 屠 蒙 池 乔 阳 郁 胥 能 苍 双闻 莘 党 翟 谭 贡 劳 逄 姬 申 扶 堵冉 宰 郦 雍 却 璩 桑 桂 濮 牛 寿 通边 扈 燕 冀 僪 浦 尚 农 温 别 庄 晏柴 瞿 阎 充 慕 连 茹 习 宦 艾 鱼 容向 古 易 慎 戈 庾 终 暨 居 衡 步都耿 满 弘 匡 国 文 寇 广 禄 阙 东欧殳 沃 利 蔚 越 夔 隆 师 巩 厍 聂晁勾 敖 融 冷 訾 辛 阚 那 简 饶 空曾毋 沙 乜 养 鞠 须 丰 巢 关 蒯 相查后 荆 红 游 竺 权 逮 盍 益 桓 公 唱万俟 司马 上官 欧阳 夏侯 诸葛 闻人 东方 赫连 皇甫 尉迟 公羊澹台 公冶 宗政 濮阳 淳于 单于 太叔 申屠 公孙 仲孙 轩辕 令狐钟离 宇文 长孙 慕容 司徒 司空 召 有 舜 丛 岳寸 贰 皇 侨 彤 竭 端 赫 实 甫 集 象翠 狂 辟 典 良 函 芒 苦 其 京 中 夕之 蹇 称 诺 来 多 繁 戊 朴 回 毓税 荤 靖 绪 愈 硕 牢 买 但 巧 枚 撒泰 秘 亥 绍 以 壬 森 斋 释 奕 姒 朋求 羽 用 占 真 穰 翦 闾 漆 贵 代 贯旁 崇 栋 告 休 褒 谏 锐 皋 闳 在 歧禾 示 是 委 钊 频 嬴 呼 大 威 昂 律冒 保 系 抄 定 化 莱 校 么 抗 祢 綦悟 宏 功 庚 务 敏 捷 拱 兆 丑 丙 畅苟 随 类 卯 俟 友 答 乙 允 甲 留 尾佼 玄 乘 裔 延 植 环 矫 赛 昔 侍 度旷 遇 偶 前 由 咎 塞 敛 受 泷 袭 衅叔 圣 御 夫 仆 镇 藩 邸 府 掌 首 员焉 戏 可 智 尔 凭 悉 进 笃 厚 仁 业肇 资 合 仍 九 衷 哀 刑 俎 仵 圭 夷徭 蛮 汗 孛 乾 帖 罕 洛 淦 洋 邶 郸郯 邗 邛 剑 虢 隋 蒿 茆 菅 苌 树 桐锁 钟 机 盘 铎 斛 玉 线 针 箕 庹 绳磨 蒉 瓮 弭 刀 疏 牵 浑 恽 势 世 仝同 蚁 止 戢 睢 冼 种 凃肖 己 泣 潜卷 脱 谬 蹉 赧 浮 顿 说 次 错 念 夙斯 完 丹 表 聊 源 姓 吾 寻 展 出 不户 闭 才 无 书 学 愚 本 性 雪 霜 烟寒 少 字 桥 板 斐 独 千 诗 嘉 扬 善揭 祈 析 赤 紫 青 柔 刚 奇 拜 佛 陀弥 阿 素 长 僧 隐 仙 隽 宇 祭 酒 淡塔 琦 闪 始 星 南 天 接 波 碧 速 禚腾 潮 镜 似 澄 潭 謇 纵 渠 奈 风 春濯 沐 茂 英 兰 檀 藤 枝 检 生 折 登驹 骑 貊 虎 肥 鹿 雀 野 禽 飞 节 宜鲜 粟 栗 豆 帛 官 布 衣 藏 宝 钞 银门 盈 庆 喜 及 普 建 营 巨 望 希 道载 声 漫 犁 力 贸 勤 革 改 兴 亓 睦修 信 闽 北 守 坚 勇 汉 练 尉 士 旅五 令 将 旗 军 行 奉 敬 恭 仪 母 堂丘 义 礼 慈 孝 理 伦 卿 问 永 辉 位让 尧 依 犹 介 承 市 所 苑 杞 剧 第零 谌 招 续 达 忻 六 鄞 战 迟 候 宛励 粘 萨 邝 覃 辜 初 楼 城 区 局 台原 考 妫 纳 泉 老 清 德 卑 过 麦 曲竹 百 福 言 第五 佟 爱 年 笪 谯 哈 墨南宫 赏 伯 佴 佘 牟 商 西门 东门 左丘 梁丘 琴后 况 亢 缑 帅 微生 羊舌 海 归 呼延 南门 东郭百里 钦 鄢 汝 法 闫 楚 晋 谷梁 宰父 夹谷 拓跋壤驷 乐正 漆雕 公西 巫马 端木 颛孙 子车 督 仉 司寇 亓官鲜于 锺离 盖 逯 库 郏 逢 阴 薄 厉 稽 闾丘公良 段干 开 光 操 瑞 眭 泥 运 摩 伟 铁"
            + " 安陵 安平 安期 安阳 白马 百里 柏侯 鲍俎 北宫 北郭 北门 北山 北唐 奔水 逼阳 宾牟 薄奚薄野曹牟 曹丘 常涛 长鱼 车非 成功 成阳 乘马 叱卢 丑门 樗里 穿封淳子答禄 达勃 达步 达奚 淡台 邓陵 第五 地连 地伦 东方 东里 东南 东宫东门 东乡 东丹 东郭 东陵 东关 东闾 东阳 东野 东莱 豆卢 斗于 都尉独孤 端木 段干 多子尔朱方雷 丰将 封人 封父 夫蒙 夫馀 浮丘 傅余干已 高车 高陵 高堂 高阳 高辛 皋落 哥舒 盖楼 庚桑 梗阳 宫孙 公羊公良 公孙 公罔 公西 公冶 公敛 公梁 公输 公上 公山 公户 公玉 公仪公仲 公坚 公伯 公祖 公乘 公晰 公族 姑布 古口 古龙 古孙 谷梁 谷浑瓜田 关龙 鲑阳 归海函治 韩馀 罕井 浩生 浩星 纥骨 纥奚 纥于 贺拨 贺兰 贺楼 赫连 黑齿黑肱 侯冈 呼延 壶丘 呼衍 斛律 胡非 胡母 胡毋 皇甫 皇父兀官 吉白 即墨 季瓜 季连 季孙 茄众 蒋丘 金齿 晋楚 京城 泾阳 九百九方 睢鸠 沮渠 巨母勘阻 渴侯 渴单 可汗 空桐 空相 昆吾老阳 乐羊 荔菲 栎阳 梁丘 梁由 梁馀 梁垣 陵阳 伶舟 冷沦 令狐 刘王柳下 龙丘 卢妃 卢蒲 鲁步 陆费 角里 闾丘马矢 麦丘 茅夷 弥牟 密革 密茅 墨夷 墨台 万俊 昌顿 慕容 木门木易南宫 南郭 南门 南荣欧侯 欧阳逄门 盆成 彭祖 平陵 平宁 破丑 仆固 濮阳漆雕 奇介 綦母 綦毋 綦连 祁连 乞伏 绮里 千代 千乘 勤宿 青阳 丘丽丘陵 屈侯 屈突 屈男 屈卢 屈同 屈门 屈引壤四 扰龙 容成 汝嫣萨孤 三饭 三闾 三州 桑丘 商瞿 上官 尚方 少师 少施 少室 少叔 少正社南 社北 申屠 申徒 沈犹 胜屠 石作 石牛 侍其 士季 士弱 士孙 士贞叔孙 叔先 叔促 水丘 司城 司空 司寇 司鸿 司马 司徒 司士 似和 素和夙沙 孙阳 索阳 索卢沓卢 太史 太叔 太阳 澹台 唐山 堂溪 陶丘 同蹄 统奚 秃发 涂钦 吐火吐贺 吐万 吐罗 吐门 吐难 吐缶 吐浑 吐奚 吐和 屯浑 脱脱 拓拨完颜 王孙 王官 王人 微生 尾勺 温孤 温稽 闻人 屋户 巫马 吾丘 无庸无钩 五鹿息夫 西陵 西乞 西钥 西乡 西门 西周 西郭 西方 西野 西宫 戏阳 瑕吕霞露 夏侯 鲜虞 鲜于 鲜阳 咸丘 相里 解枇 谢丘 新垣 辛垣 信都 信平修鱼 徐吾 宣于 轩辕 轩丘 阏氏延陵 罔法 铅陵 羊角 耶律 叶阳 伊祁 伊耆 猗卢 义渠 邑由 因孙 银齿尹文 雍门 游水 由吾 右师 宥连 於陵 虞丘 盂丘 宇文 尉迟 乐羊 乐正运奄 运期宰父 辗迟 湛卢 章仇 仉督 长孙 长儿 真鄂 正令 执头 中央 中长 中行中野 中英 中梁 中垒 钟离 钟吾 终黎 终葵 仲孙 仲长 周阳 周氏 周生朱阳 诸葛 主父 颛孙 颛顼 訾辱 淄丘 子言 子人 子服 子家 子桑 子叔子车 子阳 宗伯 宗正 宗政 尊卢 昨和 左人 左丘 左师 左行 刘文 额尔达力 蔡斯 浩赏 斛斯 夹谷 揭阳欧阳 太史 端木 上官 司马 东方 独孤 南宫 万俟 闻人 夏侯 诸葛 尉迟 公羊 赫连 澹台 皇甫 宗政 濮阳 公冶 太叔 申屠 公孙 慕容 仲孙 钟离 长孙 宇文 司徒 鲜于 司空 闾丘 子车 亓官" +
            " 司寇 巫马 公西 颛孙 壤驷 公良 漆雕 乐正 宰父 谷梁 拓跋 夹谷 轩辕 令狐 段干 百里 呼延 东郭 南门 羊舌 微生 公户 公玉 公仪 梁丘 公仲 公上 公门 公山 公坚 左丘 公伯 西门 公祖 第五 公乘 贯丘 公皙 南荣 东里 东宫 仲长 子书 子桑 即墨 达奚 褚师 吴铭";;

    public static final String [] PHONE_PREFIX_ARRAY = {"133","149","153","173","177","180","181","189","199","130","131","132","145","155","156","166","171","175","176","185","186","166","134","135","136","137","138","139","147","150","151","152","157","158","159","170","171","172","178","182","183","184","187","188","198"};

    public static final String [] CONST_NUMBER_ARR = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"};

    public static final String [] CONST_EMAIL_SUFFIX_ARRAY = {"@sotelgui.net.gn","@swiszcz.com","@netvision.net.il","@afnet.net","@xtra.co.nz","@excite.com","@zol.co.zw","@hknet.com","@amet.com.ar","@verizon.net","@biznetvigator.com","@ntc.net.np","@sina.com","@citechco.net","@t-online.de¬","@263.net","@sinos.net","@mt.net.mk","@yeah.net","@prodigy.net.mx","@pchome.com.tw","@iway.na","@ctimail.com","@westnet.com.au","@club-internet.fr","@comcast.net@cs.com","@citiz.com","@mail.mn","@hinet.net","@libero.it","@zahav.net.il@netvision.net.il","@ntlworld.com","@samara.co.zw","@live.com","@mweb.co.zw","@netzero.net","@wannado.fr","@qq.com",
            "@del3.vsnl.net.in","@twcny.rr.com","@zamnet.zm","@be-local.com","@mail.ru","@superonline.com","@cairns.net.au","@indigo.ie","@netvigator.com","@candel.co.jp","@infoclub.com.np","@xxx.meh.es","@x.cn","@topmarkeplg.com.tw","@mti.gov.na","@africaonline.co.zw","@cal3.vsnl.net.in","@nesma.net.sa","@wilnetonline.net","@aviso.ci","@163.com","@mail.com","omantel.net.om","@bigpond.net.au","@mail.sy","@vodamail.co.za","@msn.com","@yemen.net.ye@y.net.ye","@terra.es","@163.net","@googlemail.com","@yandex.ru","@hn.vnn.vn@hcm.fpt.vn@hcm.vnn.vn","@21cn.com","@mail.ruev","@yahoo.com.cn","@africaonline.co.ci","@etang.com","@bigpond.com","@gionline.com.au","@chinaren.com","@dnet.net.id","@qualitynet.net","@mail.hk.com","@adsl.loxinfo.com","@rediffmail.com","@3721.net","@vsnl.com","@net.sy","@emirates.net.ae@eim.ae","@aol.com","@hotmail.com","@sohu.com","@cyber.net.pk","@spark.net.gr","@swe.com.hk","@cytanet.com.cy","@eunet.at","@tiscali.co.uk","@inbox.com","@126.com","@scs-net.org","@yahoo.com","@tom.com","@seed.net.tw","@pacific.net.sg","@gmail.com","@sogou.com","@aim.com","@namibnet.com","@webmail.co.za","@eyou.com","@itccolp.com.hk","@sancharnet.in@ndf.vsnl.net.in","@kalianet.to","@xx.org.il","@otenet.gr","@hongkong.com","@eircom.net","@infovia.com.ar","@mynet.com","@fastmail.fm","@mos.com.np","@caron.se","@emirates.net.ae","@ttnet.net.tr","@ask.com","@0355.net","@mindspring.com","@sbcglobal.net","@56.com","@comcast.net@warwick.net","@walla.com"};

    public static final int CONST_EMAIL_SUFFIX_ARRAY_LENGTH = CONST_EMAIL_SUFFIX_ARRAY.length;

    public static final String [] CHARR_ARR = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l",
    "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"};
    public static final String DEFAULT_PASSWORD = "123456";

    public static final String [] TENANT_ARRAY = {"WQ", "YH", "LXM", "WFW"};

}
